takamarumaru/CraMagear

CramMagear_oilshock/Assets/CraMagear/Scenes/GameScene.unity
CramMagear_oilshock/Assets/CraMagear/Scripts/Character/CharacterBrain.cs

【CharacterBrain】

---

CramMagear_oilshock/Assets/CraMagear/Scenes/GameScene.unity
CramMagear_oilshock/Assets/CraMagear/Scripts/UI/PlayerGauge.cs

メインのシーンにHPバーを移植

---

CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/YOSHIZAWA/GameSceneTest.unity
CramMagear_oilshock/Assets/CraMagear/Scenes/GameScene.unity

メインシーンにミニマップアイコン移植

---

CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/YOSHIZAWA/GameSceneTest.unity

テストシーンでUIサイズ変更するか確認

---

CramMagear_oilshock/Assets/CraMagear/Assets/Materials/StageMap/TestWall.mat
CramMagear_oilshock/Assets/CraMagear/Scenes/GameScene.unity
CramMagear_oilshock/Assets/CraMagear/Scripts/UI/MiniMapCamera.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/UI/MiniMapCamera.cs.meta
CramMagear_oilshock/Assets/CraMagear/Scripts/UI/MiniMapIcon.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/UI/MiniMapIcon.cs.meta

メインのゲームシーンの隊員の挙動修正&ミニマップ調整

---

CramMagear_oilshock/Assets/CraMagear/Prefabs/Architecture/ArchitecturePrefab.prefab
CramMagear_oilshock/Assets/CraMagear/Prefabs/Architecture/turret.prefab
CramMagear_oilshock/Assets/CraMagear/Prefabs/Effect/Bullet.prefab
CramMagear_oilshock/Assets/CraMagear/Prefabs/Effect/Bullet.prefab.meta
CramMagear_oilshock/Assets/CraMagear/Prefabs/Effect/Smoke.prefab
CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/KONISHI/Scene/Effect.unity
CramMagear_oilshock/Assets/CraMagear/Scenes/GameScene.unity
CramMagear_oilshock/Assets/CraMagear/Scripts/Effect/VFX_Bullet.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/Effect/VFX_Smoke.cs

・バレットがプレイヤーの向いている方向に出るように設定
・プレイヤー、隊員、バレットにも装着
・建築時にスモークを出すように

【BulletEffect】

---

CramMagear_oilshock/Assets/CraMagear/Scenes/GameScene.unity

【PortToMain】

---

CramMagear_oilshock/Assets/CraMagear/Prefabs/Effect/Impact.prefab
CramMagear_oilshock/Assets/CraMagear/Prefabs/Effect/Impact.prefab.meta
CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/KONISHI/Scene/Effect.unity
CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/KONISHI/VFX/Impact.vfx
CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/KONISHI/VFX/Impact.vfx.meta
CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/KONISHI/VFX/Smoke.vfx
CramMagear_oilshock/Assets/CraMagear/Scripts/Effect/VFX_Bullet.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/Effect/VFX_Common.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/Effect/VFX_Impact.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/Effect/VFX_Impact.cs.meta
CramMagear_oilshock/Assets/CraMagear/Scripts/Effect/VFX_Smoke.cs

着弾のエフェクトを作成

---

CramMagear_oilshock/Assets/CraMagear/Scenes/GameScene.unity

UIエラー修正&敵の頭上にHPバー移植

---

CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/YOSHIZAWA/GameSceneTest#2.unity
CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/YOSHIZAWA/GameSceneTest#2.unity.meta
CramMagear_oilshock/Assets/CraMagear/Scenes/GameScene.unity

ゲームシーンのUI面の修正

---

CramMagear_oilshock/Assets/CraMagear/Assets/Materials/arrow.mat
CramMagear_oilshock/Assets/CraMagear/Assets/Materials/arrow.mat.meta
CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/YOSHIZAWA/GameSceneTest#2.unity
CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/YOSHIZAWA/仮ステージ.unity
CramMagear_oilshock/Assets/CraMagear/Scripts/UI/EHPBarRotate.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/UI/F1EnemyPopIcon.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/UI/F1EnemyPopIcon.cs.meta
CramMagear_oilshock/Assets/CraMagear/Scripts/UI/PlayerLookEnemy.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/UI/PlayerLookEnemy.cs.meta
CramMagear_oilshock/Assets/CraMagear/Scripts/UI/Test/MoveTestUi.cs

ミニマップに敵表示#4

---

CramMagear_oilshock/Assets/CraMagear/Prefabs/Effect/Impact.prefab
CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/KONISHI/Scene/Effect.unity
CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/KONISHI/Scene/GameScene.unity
CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/KONISHI/Scene/GameScene.unity.meta
CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/KONISHI/VFX/Impact.vfx

着弾のエフェクトを修正

---

CramMagear_oilshock/Assets/CraMagear/Prefabs/Architecture/turret.prefab
CramMagear_oilshock/Assets/CraMagear/Prefabs/Effect/MembersBulletAndTrail.prefab
CramMagear_oilshock/Assets/CraMagear/Prefabs/Effect/MembersBulletAndTrail.prefab.meta
CramMagear_oilshock/Assets/CraMagear/Prefabs/Effect/TurretBullet.prefab
CramMagear_oilshock/Assets/CraMagear/Scenes/GameScene.unity

【BulletRecify】

---

CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/YOSHIZAWA/GameSceneTest#2.unity
CramMagear_oilshock/Assets/CraMagear/Scripts/UI/Pase1Timer.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/UI/Pase1Timer.cs.meta

Phase1のタイマー再度追加

---

CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/FUKAZAWA/CharaBrainRevise.unity
CramMagear_oilshock/Assets/CraMagear/Scripts/Character/Enemy/EnemyAI.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/Character/Member/MemberAI.cs

【ChractorBrain】

---

CramMagear_oilshock/Assets/CraMagear/Scenes/GameScene.unity

ゲームシーンにスキルリキャストと銃弾スロット移植

---

CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/YOSHIZAWA/GameScene#3.unity
CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/YOSHIZAWA/GameScene#3.unity.meta

コンポーネントが謎に消えた現象の対処

---

CramMagear_oilshock/Assets/CraMagear/Assets/Inputs/PlayerInputManager.inputactions
CramMagear_oilshock/Assets/CraMagear/Prefabs/Architecture/turret2.prefab
CramMagear_oilshock/Assets/CraMagear/Prefabs/Architecture/turret2.prefab.meta
CramMagear_oilshock/Assets/CraMagear/Prefabs/Architecture/turret3.prefab
CramMagear_oilshock/Assets/CraMagear/Prefabs/Architecture/turret3.prefab.meta
CramMagear_oilshock/Assets/CraMagear/Prefabs/Architecture/turretGuide.prefab
CramMagear_oilshock/Assets/CraMagear/Prefabs/Architecture/turretGuide2.prefab
CramMagear_oilshock/Assets/CraMagear/Prefabs/Architecture/turretGuide2.prefab.meta
CramMagear_oilshock/Assets/CraMagear/Prefabs/Architecture/turretGuide3.prefab
CramMagear_oilshock/Assets/CraMagear/Prefabs/Architecture/turretGuide3.prefab.meta
CramMagear_oilshock/Assets/CraMagear/Scenes/GameScene.unity
CramMagear_oilshock/Assets/CraMagear/Scripts/Input/PlayerInputManager.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/System/ArchitectureCreator.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/System/MembersAdministrator.cs
CramMagear_oilshock/Assets/CraMagear/ThirdPartyAssets/Models/Turrets Pack/Materials/turret_2Guide.mat
CramMagear_oilshock/Assets/CraMagear/ThirdPartyAssets/Models/Turrets Pack/Materials/turret_2Guide.mat.meta
CramMagear_oilshock/Assets/CraMagear/ThirdPartyAssets/Models/Turrets Pack/Materials/turret_4Guide.mat
CramMagear_oilshock/Assets/CraMagear/ThirdPartyAssets/Models/Turrets Pack/Materials/turret_4Guide.mat.meta

【Architecture】

---

CramMagear_oilshock/Assets/CraMagear/Scenes/GameScene.unity

城のHPバー移植&フェーズ1のタイマーが移植できてなかったので移植

城のHPバー移植&フェーズ1のタイマーが移植できてなかったので移植

---

CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/KONISHI/VFX/Impact.vfx
CramMagear_oilshock/Assets/CraMagear/Scenes/GameScene.unity
CramMagear_oilshock/Assets/CraMagear/Scripts/Character/BulletShot.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/System/ArchitectureCreator.cs

【BulletSwitching】

---

CramMagear_oilshock/Assets/CraMagear/Prefabs/Architecture/LaserTurret.prefab
CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/MORIE/LaserTurret.unity
CramMagear_oilshock/Assets/CraMagear/Scenes/GameScene.unity
CramMagear_oilshock/Assets/CraMagear/Scripts/Character/TurretController.cs

【LaserTurret】

---

CramMagear_oilshock/Assets/CraMagear/Prefabs/Effect/Turret/Explosion/ExplosionGuide.prefab
CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/MORIE/Skill.unity
CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/MORIE/Skill.unity.meta
CramMagear_oilshock/Assets/CraMagear/Scripts/Character/BulletShot.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/System/MembersAdministrator.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/System/Skill.meta
CramMagear_oilshock/Assets/CraMagear/Scripts/System/Skill/SkillBase.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/System/Skill/SkillBase.cs.meta
CramMagear_oilshock/Assets/CraMagear/Scripts/System/Skill/SkillManager.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/System/Skill/SkillManager.cs.meta
CramMagear_oilshock/Assets/CraMagear/Scripts/System/Skill/Skill_AddArchitecture.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/System/Skill/Skill_AddArchitecture.cs.meta
CramMagear_oilshock/Assets/CraMagear/Scripts/System/Skill/Skill_AddBullet.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/System/Skill/Skill_AddBullet.cs.meta
CramMagear_oilshock/Assets/CraMagear/Scripts/System/Skill/Skill_AddMember.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/System/Skill/Skill_AddMember.cs.meta

・スキル管理クラスとスキル実行クラスを作成
・inspector上から建築物追加の有無を変更できるように

【SkillManager】

---

CramMagear_oilshock/Packages/manifest.json
CramMagear_oilshock/Packages/packages-lock.json
CramMagear_oilshock/ProjectSettings/EditorSettings.asset

・Unityで動画を撮影できるようになったからみんなツイートするんやで

【UnityRecorder】

---

CramMagear_oilshock/Assets/CraMagear/Scenes/GameScene.unity
CramMagear_oilshock/Assets/CraMagear/Scripts/Character/Enemy/TurretChaseEnemyAI.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/Character/LookAtTarget.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/Input/EnemyInputProvider.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/Input/TargetSearcher.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/System/ArchitectureCreator.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/System/IngredientsDrop.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/System/IngredientsDrop.cs.meta
CramMagear_oilshock/Assets/CraMagear/Scripts/System/IngredientsManager.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/System/IngredientsManager.cs.meta
CramMagear_oilshock/Assets/CraMagear/ThirdPartyAssets/Blink/Art/Animations/Animations_Starter_Pack/Combat/Death.fbx.meta

・素材管理クラスを作成
・敵から素材がドロップするようにした
・建築に素材を使用するようにした

【ingredients】

---

CramMagear_oilshock/Assets/CraMagear/Prefabs/Effect/EnemySpawn.prefab
CramMagear_oilshock/Assets/CraMagear/Prefabs/Effect/EnemySpawn.prefab.meta
CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/KONISHI/Scene/Effect.unity
CramMagear_oilshock/Assets/CraMagear/Scenes/ExperimentalScene/KONISHI/Script/VFX_EnemySpawn.cs
CramMagear_oilshock/Assets/CraMagear/Scenes/GameScene.unity
CramMagear_oilshock/Assets/CraMagear/Scripts/Character/BulletShot.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/System/GameAadministrator.cs

【EnemySpawnEffect】

---

CramMagear_oilshock/Assets/CraMagear/Scenes/GameScene.unity
CramMagear_oilshock/Assets/CraMagear/Scripts/Character/BulletShot.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/Input/PlayerInputManager.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/System/GameAadministrator.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/UI/SkillUI/BulletChangeCount.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/UI/SkillUI/WarpBulletUI.cs

【SkillRecast】

---

CramMagear_oilshock/Assets/CraMagear/Assets/Animations/Animations/SD_unitychan_motion_humanoid.fbx.meta
CramMagear_oilshock/Assets/CraMagear/Assets/Models/Toko/AC_CharaBrain.controller
CramMagear_oilshock/Assets/CraMagear/Scenes/GameScene.unity
CramMagear_oilshock/Assets/CraMagear/Scripts/Animation/CharacterAnimationEventReceiver.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/Character/CharacterBrain.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/Character/DamageJudgeCastle.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/Character/MainObjectParameter.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/Character/RandomBorn.cs
CramMagear_oilshock/Assets/CraMagear/Scripts/System/GameAadministrator.cs

・最終フェーズが終わった際に敵をすべて倒したらクリア
・プレイヤーのHPがなくなった時にゲームオーバーシーンに
・城のHPがなくなった時にゲームオーバーシーンに

【AddGameOverClear】
